/**
 * AUTO-GENERATED (scratch/_gen_headermap.mjs từ scratch/_v1_headers.json).
 * Map HEADER tiếng Việt của sheet "Blackstones Data Sync V1" -> KEY ASCII ổn định.
 * crmSheetSync dùng map này để JSONB giữ key ASCII (account_code, cf_cccd_kh, status...)
 * mà toàn bộ app + sql/migration_crm_v1_rebuild.sql đang phụ thuộc.
 * KHÔNG sửa tay — chỉnh field ở blackstones_data_sync_v1.gs rồi sinh lại.
 */
export const CRM_HEADER_MAP: Record<string, Record<string, string>> = {
  crm_khach_hang: {
    'ID hệ thống': 'id',
    'Mã KH': 'account_code',
    'Họ tên khách hàng': 'account_name',
    'Mô tả': 'description',
    'Địa chỉ thường trú': 'billing_address_street',
    'Điện thoại': 'phone_office',
    'Email': 'email',
    'Email người phụ trách': 'mgr_email',
    'Người phụ trách': 'mgr_display_name',
    'Website': 'website',
    'Logo': 'logo',
    'Ngày sinh': 'birthday',
    'Mã số thuế': 'sic_code',
    'Ngày tạo': 'created_at',
    'Ngày cập nhật': 'updated_at',
    'Nhóm KH (ID)': 'nhom_kh_id',
    'Nguồn (ID)': 'nguon_id',
    'Mã quan hệ': 'relation_id',
    'Mối quan hệ': 'relation_name',
    'Giới tính (mã)': 'gender',
    'Tổng doanh thu': 'total_revenue',
    'Liên hệ - Tên': 'lh_first_name',
    'Liên hệ - Xưng hô': 'lh_honorifics',
    'Liên hệ - Chức vụ': 'lh_title',
    'Liên hệ - SĐT': 'lh_phone_home',
    'Liên hệ - Email': 'lh_email',
    'Liên hệ - Địa chỉ': 'lh_address',
    'Liên hệ - Giới tính': 'lh_gender_name',
    'Liên hệ - Ngày sinh': 'lh_birthdate',
    'Liên hệ - Là LH chính': 'lh_is_primary',
    'Liên hệ - Ghi chú': 'lh_description',
    'Liên hệ (thêm)': 'lh_them',
    'Mã hội viên': 'cf_ma_hoi_vien',
    'Gói dịch vụ dự kiến': 'cf_goi_dich_vu',
    'Trạng thái hội viên': 'cf_trang_thai_hoi_vien',
    'Ngày tham gia': 'cf_ngay_tham_gia',
    'Doanh thu Membership': 'cf_doanh_thu_membership',
    'Số CCCD': 'cf_so_cccd',
    'Số TK ngân hàng': 'cf_so_tk_ngan_hang',
    'Tên ngân hàng': 'cf_ten_ngan_hang',
    'Địa chỉ liên hệ': 'cf_dia_chi_lien_he',
    'Họ tên người mất': 'cf_ho_ten_nguoi_mat',
    'Ngày mất': 'cf_ngay_mat',
    'Thời gian tổ chức đám': 'cf_thoi_gian_to_chuc_dam',
    'Địa chỉ chôn cất': 'cf_dia_chi_chon_cat',
    'Quốc gia': 'country_name',
    'Mã quốc gia': 'country_code',
    'Ngành (tên)': 'industry_names',
    'Quốc gia (ID)': 'country_id',
    'Tỉnh/TP (ID)': 'province_id',
    'Quận/Huyện (ID)': 'district_id',
    'Phường/Xã (ID)': 'ward_id',
    'Ngành (ID)': 'nganh_id',
    'Người phụ trách (ID)': 'account_manager',
    'Người được chia sẻ': 'nguoi_duoc_chia_se',
    'Nhóm KH': 'nhom_kh',
    'Tỉnh/TP': 'tinh_tp',
    'Quận/Huyện': 'quan_huyen',
    'Phường/Xã': 'phuong_xa',
    'Giới tính': 'gioi_tinh_label',
    'Nguồn': 'nguon',
    'Ngành': 'nganh',
    'Mối quan hệ (nhãn)': 'quan_he_label',
    'Điểm thưởng': 'total_point_bonus',
    'Tiền thưởng tích lũy': 'total_cash_bonus',
    'Hoạt động gần nhất (unix)': 'last_active',
    'Số ngày hoạt động': 'last_active_day',
    'Hoạt động gần nhất': 'last_active_desc',
    'Link hoạt động': 'last_active_url',
  },
  crm_don_ban: {
    'ID hệ thống': 'id',
    'Mã đơn': 'order_code',
    'Ngày đơn hàng': 'order_date',
    'Ngày tạo': 'created_at',
    'Ngày cập nhật': 'updated_at',
    'Trạng thái (mã)': 'status',
    'Trạng thái': 'status_label',
    'Tình trạng thanh toán': 'payment_status',
    'Đã tất toán': 'has_pay_off',
    'Mã KH (ID)': 'account_id',
    'Mã KH': 'account_code',
    'Email KH': 'account_email',
    'SĐT KH': 'account_phone',
    'Địa chỉ': 'account_address',
    'Tên người liên hệ': 'contact_name',
    'SĐT liên hệ': 'contact_phone',
    'Email liên hệ': 'contact_email',
    'Tổng tiền': 'real_amount',
    'Đã thanh toán': 'f_amount',
    'VAT (tiền)': 'vat_amount',
    'Chiết khấu (%)': 'discount',
    'Chiết khấu (tiền)': 'discount_amount',
    'Người phụ trách (ID)': 'assigned_user',
    'Người phụ trách': 'assigned_user_name',
    'Đồng bộ sổ quỹ': 'safebook_synchronized',
    'Kho (ID)': 'store_id',
    'Nguồn (ID)': 'src_id',
    'Nguồn đơn': 'src_name',
    'Mã vận đơn': 'lading_code',
    'Trạng thái vận đơn (mã)': 'lading_status',
    'Trạng thái vận đơn': 'lading_status_title',
    'Link theo dõi': 'tracking_url',
    'Vận đơn - Trạng thái': 'vandon_status',
    'Vận đơn - Link theo dõi': 'vandon_tracking_url',
    'Vận đơn (thêm)': 'vandon_them',
    'Mã HĐ liên kết': 'contract_id',
    'SP - Mã SP': 'sp_product_code',
    'SP - Tên SP': 'sp_product_name',
    'SP - ĐVT': 'sp_unit_name',
    'SP - Số lượng': 'sp_quantity',
    'SP - Đơn giá': 'sp_price',
    'SP - Thành tiền': 'sp_amount',
    'SP - VAT (%)': 'sp_vat',
    'SP - VAT (tiền)': 'sp_vat_amount',
    'SP - Ghi chú': 'sp_note',
    'SP - SL nhập': 'sp_in_quantity',
    'SP - SL xuất': 'sp_out_quantity',
    'SP - SL trả': 'sp_repay_quantity',
    'SP - Giá nhập': 'sp_price_in',
    'SP - Giảm tiền mặt': 'sp_cash_discount',
    'SP - Khuyến mãi': 'sp_product_sale_off',
    'SP - Đơn giá gốc': 'sp_origin_amount',
    'SP - Chịu thuế': 'sp_is_taxable',
    'SP - Là dịch vụ': 'sp_services',
    'SP - Có tồn kho': 'sp_has_inventory',
    'SP - Mã SP (ID)': 'sp_product_id',
    'SP (thêm)': 'sp_them',
    'Kỳ TT - Tên kỳ': 'kytt_title',
    'Kỳ TT - Mô tả': 'kytt_description',
    'Kỳ TT - Tỷ lệ (%)': 'kytt_percent',
    'Kỳ TT - Số tiền': 'kytt_amount',
    'Kỳ TT - Ngày thanh toán': 'kytt_pay_day',
    'Kỳ TT - Trạng thái': 'kytt_status',
    'Kỳ TT - Mã phiếu TT': 'kytt_payment_id',
    'Kỳ TT - Mã phiếu (sheet)': 'kytt_payment_sheet_id',
    'Kỳ TT - Mã đính kèm': 'kytt_attachment_code',
    'Kỳ TT (thêm)': 'kytt_them',
    'Họ tên người mất': 'cf_ho_va_ten_nguoi_mat',
    'Ngày tháng năm sinh': 'cf_ngay_thang_nam_sinh',
    'Ngày mất': 'cf_ngay_mat',
    'Quan hệ với người mất': 'cf_moi_quan_he_voi_nguoi_mat',
    'Địa chỉ thường trú': 'cf_dia_chi_thuong_tru',
    'Nguyên quán': 'cf_nguyen_quan',
    'Số điện thoại': 'cf_so_dien_thoai',
    'Email': 'cf_email',
    'Địa chỉ liên hệ': 'cf_dia_chi_lien_he',
    'Địa chỉ tổ chức': 'cf_dia_chi_to_chuc',
    'Địa chỉ chôn cất/hỏa táng': 'cf_dia_chi_chon_cat_hoa_tang',
    'Thời gian tổ chức': 'cf_thoi_gian_to_chuc',
    'Ngày nhập quan': 'cf_ngay_nhap_quan',
    'Ngày di quan': 'cf_ngay_di_quan',
    'Ngày hết hạn': 'cf_ngay_het_han',
    'Người giới thiệu': 'cf_nguoi_gioi_thieu',
    'Phiếu xuất kho': 'sheet_outs',
    'Đính kèm': 'attachments',
  },
  crm_don_mua: {
    'ID hệ thống': 'id',
    'Mã đơn': 'order_code',
    'Ngày đơn hàng': 'order_date',
    'Ngày tạo': 'created_at',
    'Ngày cập nhật': 'updated_at',
    'Trạng thái (mã)': 'status',
    'Tổng tiền': 'real_amount',
    'Đã thanh toán': 'f_amount',
    'Chiết khấu (%)': 'discount',
    'Chiết khấu (tiền)': 'discount_amount',
    'VAT (tiền)': 'vat_amount',
    'Mã KH (ID)': 'account_id',
    'Mã KH': 'account_code',
    'Email KH': 'account_email',
    'SĐT KH': 'account_phone',
    'Địa chỉ': 'account_address',
    'Người phụ trách (ID)': 'assigned_user',
    'Người phụ trách': 'assigned_user_name',
    'Tên người liên hệ': 'contact_name',
    'SĐT liên hệ': 'contact_phone',
    'Email liên hệ': 'contact_email',
    'SP - Mã SP': 'sp_product_code',
    'SP - Tên SP': 'sp_product_name',
    'SP - ĐVT': 'sp_unit_name',
    'SP - Số lượng': 'sp_quantity',
    'SP - Đơn giá': 'sp_price',
    'SP - Thành tiền': 'sp_amount',
    'SP - VAT (%)': 'sp_vat',
    'SP - VAT (tiền)': 'sp_vat_amount',
    'SP - Ghi chú': 'sp_note',
    'SP - SL nhập': 'sp_in_quantity',
    'SP - SL xuất': 'sp_out_quantity',
    'SP - SL trả': 'sp_repay_quantity',
    'SP - Giá nhập': 'sp_price_in',
    'SP - Giảm tiền mặt': 'sp_cash_discount',
    'SP - Khuyến mãi': 'sp_product_sale_off',
    'SP - Đơn giá gốc': 'sp_origin_amount',
    'SP - Chịu thuế': 'sp_is_taxable',
    'SP - Là dịch vụ': 'sp_services',
    'SP - Có tồn kho': 'sp_has_inventory',
    'SP - Mã SP (ID)': 'sp_product_id',
    'SP (thêm)': 'sp_them',
    'detail_custom_fields': 'detail_custom_fields',
    'Đính kèm': 'attachments',
    'Mã HĐ liên kết': 'contract_id',
  },
  crm_hop_dong_ban: {
    'ID hệ thống': 'id',
    'Mã hợp đồng': 'contract_code',
    'Tên hợp đồng': 'contract_name',
    'Trạng thái (mã)': 'contract_status',
    'Trạng thái': 'contract_status_label',
    'Nhãn HĐ mới': 'new_contract_label',
    'Loại HĐ': 'contract_type',
    'Số hợp đồng': 'number_of_contract',
    'Ngày hiệu lực': 'effective_date',
    'Ngày hết hạn': 'expiration_date',
    'Còn lại (ngày)': 'expiration_day_remain',
    'Ngày ký': 'contract_date',
    'Bắt đầu thực tế': 'start_actual_time',
    'Kết thúc thực tế': 'end_actual_time',
    'Số lần dùng (mã)': 'contract_used',
    'Số lần dùng': 'contract_used_label',
    'Đã thực hiện': 'performed',
    'Số lần thực hiện': 'number_performed',
    'Bên bán (ID)': 'vendor_account_id',
    'Bên bán': 'vendor_account_name',
    'Bên bán - Địa chỉ': 'vendor_account_address',
    'Bên bán - SĐT': 'vendor_account_phone',
    'Bên bán - Fax': 'vendor_account_fax',
    'Bên bán - PT (ID)': 'vendor_account_manager',
    'Bên bán - Người phụ trách': 'vendor_account_manager_name',
    'Bên bán - Người liên hệ': 'vendor_contact_name',
    'Bên bán - Chức vụ LH': 'vendor_contact_title',
    'Bên bán - LH (ID)': 'vendor_contact_id',
    'Bên bán - Vị trí': 'vendor_positions',
    'Bên bán - NH (địa chỉ)': 'vendor_bank_address',
    'Bên bán - Số TK': 'vendor_bank_account_number',
    'Bên bán - MST': 'vendor_sic_code',
    'Bên mua (ID)': 'buyers_account_id',
    'Bên mua': 'buyers_account_name',
    'Bên mua - Địa chỉ': 'buyers_account_address',
    'Bên mua - SĐT': 'buyers_account_phone',
    'Bên mua - Fax': 'buyers_account_fax',
    'Bên mua - Người liên hệ': 'buyers_contact_name',
    'Bên mua - LH (ID)': 'buyers_contact_id',
    'Bên mua - Vị trí': 'buyers_positions',
    'Bên mua - NH (địa chỉ)': 'buyers_bank_address',
    'Bên mua - Số TK': 'buyers_bank_account_number',
    'Bên mua - MST': 'buyers_sic_code',
    'Giá trị sau VAT': 'after_vat',
    'Chiết khấu (%)': 'discount',
    'Chiết khấu (tiền)': 'discount_amount',
    'VAT (%)': 'vat',
    'VAT (tiền)': 'vat_amount',
    'HT thanh toán (mã)': 'payment_methods',
    'Hình thức thanh toán': 'payment_methods_name',
    'Giá trị thực hiện': 'actual_value',
    'Tổng đã thanh toán': 'total_payment',
    'Tổng tiền đơn bán': 'total_sale_order_real_amount',
    'Còn lại (đơn bán)': 'total_sale_order_remain_amount',
    'Đã thu (đơn bán)': 'total_sale_order_f_amount',
    'Báo giá (ID)': 'quote_id',
    'Mã báo giá': 'quote_code',
    'Dự án': 'project_name',
    'Địa chỉ dự án': 'project_address',
    'Mã HĐ gốc': 'contract_origin_code',
    'HĐ cha (ID)': 'contract_parent_id',
    'Người tạo (ID)': 'create_user',
    'Người tạo': 'create_user_display_name',
    'Người duyệt (ID)': 'approved_by',
    'Thời điểm duyệt': 'approved_at',
    'Người duyệt': 'approved_by_display_name',
    'Điều khoản - Tên điều khoản': 'dieu_khoan_term_name',
    'Điều khoản - Nội dung điều khoản': 'dieu_khoan_term_des',
    'Điều khoản (thêm)': 'dieu_khoan_them',
    'Kỳ TT - Tên kỳ': 'kytt_title',
    'Kỳ TT - Mô tả': 'kytt_description',
    'Kỳ TT - Tỷ lệ (%)': 'kytt_percent',
    'Kỳ TT - Số tiền': 'kytt_amount',
    'Kỳ TT - Ngày thanh toán': 'kytt_pay_day',
    'Kỳ TT - Trạng thái': 'kytt_status',
    'Kỳ TT - Mã phiếu TT': 'kytt_payment_id',
    'Kỳ TT - Mã phiếu (sheet)': 'kytt_payment_sheet_id',
    'Kỳ TT - Mã đính kèm': 'kytt_attachment_code',
    'Kỳ TT (thêm)': 'kytt_them',
    'CCCD khách hàng': 'cf_cccd_kh',
    'Người thụ hưởng 1': 'cf_nguoi_thu_huong_so_1',
    'VNeID thụ hưởng 1': 'cf_vneid_nguoi_thu_huong_1',
    'SĐT thụ hưởng 1': 'cf_so_dien_thoai_nguoi_thu_huong_01',
    'Địa chỉ thụ hưởng 1': 'cf_dia_chi_nguoi_thu_huong_01',
    'Người thụ hưởng 2': 'cf_nguoi_thu_huong_02',
    'VNeID thụ hưởng 2': 'cf_vneid_nguoi_thu_huong_02',
    'SĐT thụ hưởng 2': 'cf_so_dien_thoai_nguoi_thu_huong_02',
    'Địa chỉ thụ hưởng 2': 'cf_dia_chi_nguoi_thu_huong_02',
    'Email người mua': 'cf_email_nguoi_mua',
  },
  crm_hop_dong_mua: {
    'ID hệ thống': 'id',
    'Mã hợp đồng': 'contract_code',
    'Tên hợp đồng': 'contract_name',
    'Trạng thái (mã)': 'contract_status',
    'Trạng thái': 'contract_status_label',
    'Loại HĐ': 'contract_type',
    'Số hợp đồng': 'number_of_contract',
    'Ngày hiệu lực': 'effective_date',
    'Ngày hết hạn': 'expiration_date',
    'Còn lại (ngày)': 'expiration_day_remain',
    'Ngày ký': 'contract_date',
    'Bên bán (ID)': 'vendor_account_id',
    'Bên bán': 'vendor_account_name',
    'Bên bán - SĐT': 'vendor_account_phone',
    'Bên bán - Người liên hệ': 'vendor_contact_name',
    'Bên mua (ID)': 'buyers_account_id',
    'Bên mua': 'buyers_account_name',
    'Bên mua - SĐT': 'buyers_account_phone',
    'Bên mua - MST': 'buyers_sic_code',
    'Giá trị sau VAT': 'after_vat',
    'VAT (%)': 'vat',
    'VAT (tiền)': 'vat_amount',
    'Chiết khấu (%)': 'discount',
    'Chiết khấu (tiền)': 'discount_amount',
    'Hình thức thanh toán': 'payment_methods_name',
    'Giá trị thực hiện': 'actual_value',
    'Tổng đã thanh toán': 'total_payment',
    'Tổng tiền đơn mua': 'total_purchase_order_real_amount',
    'Còn lại (đơn mua)': 'total_purchase_order_remain_amount',
    'Đã thu (đơn mua)': 'total_purchase_order_f_amount',
    'Người tạo': 'create_user_display_name',
    'Người duyệt': 'approved_by_display_name',
    'Thời điểm duyệt': 'approved_at',
    'Điều khoản - Tên điều khoản': 'dieu_khoan_term_name',
    'Điều khoản - Nội dung điều khoản': 'dieu_khoan_term_des',
    'Điều khoản (thêm)': 'dieu_khoan_them',
    'Kỳ TT - Tên kỳ': 'kytt_title',
    'Kỳ TT - Mô tả': 'kytt_description',
    'Kỳ TT - Tỷ lệ (%)': 'kytt_percent',
    'Kỳ TT - Số tiền': 'kytt_amount',
    'Kỳ TT - Ngày thanh toán': 'kytt_pay_day',
    'Kỳ TT - Trạng thái': 'kytt_status',
    'Kỳ TT - Mã phiếu TT': 'kytt_payment_id',
    'Kỳ TT - Mã phiếu (sheet)': 'kytt_payment_sheet_id',
    'Kỳ TT - Mã đính kèm': 'kytt_attachment_code',
    'Kỳ TT (thêm)': 'kytt_them',
    'detail_custom_fields': 'detail_custom_fields',
  },
  crm_bao_gia: {
    'ID hệ thống': 'id',
    'Mã báo giá': 'quote_code',
    'Số báo giá': 'quote_number',
    'Ngày báo giá': 'quote_date',
    'Trạng thái (mã)': 'status',
    'Trạng thái': 'status_title',
    'Tổng tiền': 'amount',
    'Giá trị sau VAT': 'after_vat',
    'VAT (%)': 'vat',
    'VAT (tiền)': 'vat_amount',
    'Chiết khấu (%)': 'discount',
    'Chiết khấu (tiền)': 'discount_amount',
    'Phí vận chuyển': 'transport_amount',
    'Phí lắp đặt': 'installation_amount',
    'Mã KH (ID)': 'account_id',
    'Mã KH': 'account_code',
    'Họ tên khách hàng': 'account_name',
    'SĐT KH': 'account_phone',
    'Người lập': 'user_name',
    'Người phụ trách': 'assigned_user_name',
    'Người duyệt': 'approval_user_name',
    'Ngày tạo': 'created_at',
  },
  crm_san_pham: {
    'ID hệ thống': 'id',
    'Mã SP': 'product_code',
    'Tên SP': 'product_name',
    'Nhóm SP (ID)': 'category_id',
    'Nhóm SP': 'category_name',
    'ĐVT (ID)': 'unit_id',
    'ĐVT': 'unit_name',
    'Là dịch vụ': 'services',
    'Hãng SX (ID)': 'manufacturer_id',
    'Hãng SX': 'manufacturer_name',
    'Xuất xứ (ID)': 'origin_id',
    'Xuất xứ': 'origin_name',
    'Giá niêm yết': 'cover_price',
    'Giá sỉ': 'price_wholesale',
    'Chiết khấu sỉ': 'discount_wholesale',
    'Giá online': 'price_online',
    'Chiết khấu online': 'discount_online',
    'Giá nhập TB': 'price_average_in',
    'Chiết khấu nhập': 'discount_in',
    'Giá khuyến mãi': 'saleoff_price',
    'Chiết khấu (%)': 'discount',
    'VAT (%)': 'product_vat',
    'Khối lượng': 'weight',
    'Mô tả ngắn': 'short_description',
    'Mô tả': 'description',
    'Ảnh đại diện': 'featured_image',
    'Ngày tạo': 'created_at',
    'Ngày cập nhật': 'updated_at',
    'Hoạt động gần nhất (unix)': 'last_active',
    'Ảnh 1': 'anh_1',
    'Ảnh 2': 'anh_2',
    'Ảnh 3': 'anh_3',
    'Ảnh 4': 'anh_4',
    'Ảnh 5': 'anh_5',
    'Ảnh 6': 'anh_6',
    'variant_attributes': 'variant_attributes',
    'variant_attribute_values': 'variant_attribute_values',
    'detail_custom_fields': 'detail_custom_fields',
  },
  crm_cong_viec: {
    'ID hệ thống': 'id',
    'Mã công việc': 'task_code',
    'Tên công việc': 'task_name',
    'Mô tả': 'task_description',
    'Bắt đầu': 'task_start_date',
    'Kết thúc': 'task_end_date',
    'Trạng thái (mã)': 'task_status',
    'Trạng thái': 'task_status_title',
    'Tiến độ (%)': 'task_progress',
    'Quan trọng': 'user_important',
    'Người nhận (ID)': 'task_receiver',
    'Người nhận': 'task_receiver_display_name',
    'Email người nhận': 'task_receiver_email',
    'SĐT người nhận': 'task_receiver_phone',
    'Avatar người nhận': 'task_receiver_avatar',
    'Màu nhãn': 'task_color',
    'Dự án (ID)': 'project_id',
    'Dự án': 'project_name',
    'Số thông báo': 'notifications_count',
    'KH liên quan - Mã KH': 'kh_account_code',
    'KH liên quan - Tên KH': 'kh_account_name',
    'KH liên quan - SĐT KH': 'kh_account_phone',
    'KH liên quan - Email KH': 'kh_account_email',
    'KH liên quan - Địa chỉ KH': 'kh_account_address',
    'KH liên quan - Mối quan hệ': 'kh_relation_name',
    'KH liên quan - Người phụ trách': 'kh_account_manager',
    'KH liên quan - Tên liên hệ': 'kh_contact_name',
    'KH liên quan - SĐT liên hệ': 'kh_contact_phone',
    'KH liên quan - Email liên hệ': 'kh_contact_email',
    'KH liên quan (thêm)': 'kh_them',
    'custom_fields': 'custom_fields',
    'detail_custom_fields': 'detail_custom_fields',
  },
  crm_co_hoi: {
    'ID hệ thống': 'id',
    'Mã cơ hội': 'opportunity_code',
    'Tên cơ hội': 'opportunity_name',
    '% thắng': 'probability',
    'Trạng thái CH (mã)': 'opportunity_status',
    'Trạng thái cơ hội': 'opportunity_status_name',
    'Trạng thái (mã)': 'status',
    'Trạng thái': 'status_label',
    'Mã KH (ID)': 'account_id',
    'Họ tên khách hàng': 'account_name',
    'Điện thoại': 'phone_office',
    'Email KH': 'account_email',
    'campaign_id': 'campaign_id',
    'Tên chiến dịch': 'campaign_name',
    'Người phụ trách (ID)': 'responsible',
    'Người phụ trách': 'c_display_name',
    'Người nhận (ID)': 'recipient',
    'Người nhận': 'rcpt_display_name',
    'Vai trò người nhận': 'rcpt_role_name',
    'Phòng ban người nhận': 'rcpt_department_name',
    'Avatar người nhận': 'rcpt_avatar',
    'Người tạo (ID)': 'create_user',
    'Ngày tạo': 'created_at',
    'Thời gian đăng ký': 'time_registed',
    'define_fields': 'define_fields',
  },
  crm_chien_dich: {
    'ID hệ thống': 'id',
    'Mã chiến dịch': 'campaign_code',
    'Tên chiến dịch': 'campaign_name',
    'Người tạo (ID)': 'create_user',
    'Người phụ trách (ID)': 'responsible',
    'Thời gian đăng ký': 'time_registed',
    'Cho phép trùng cơ hội': 'allow_duplicate_opp',
    'Khóa': 'is_lock',
    'Bước 1': 'buoc_1',
    'Bước 2': 'buoc_2',
    'Bước 3': 'buoc_3',
    'Bước 4': 'buoc_4',
    'Bước 5': 'buoc_5',
    'Bước 6': 'buoc_6',
    'Bước 7': 'buoc_7',
    'Bước 8': 'buoc_8',
    'Người LQ - ID': 'nguoi_user_id',
    'Người LQ - Nhận cơ hội': 'nguoi_accept_opp',
    'Người LQ - % chia': 'nguoi_divided_percent',
    'Người LQ (thêm)': 'nguoi_them',
    'cause_types': 'cause_types',
  },
  crm_nguoi_dung: {
    'ID người dùng': 'user_id',
    'Tên người liên hệ': 'contact_name',
    'Người lập': 'user_name',
    'Phòng ban (ID)': 'dept_id',
    'Phòng ban': 'dept_name',
    'Email': 'email',
    'SĐT': 'contact_mobile',
    'Máy nhánh': 'extensions',
  },
  crm_kho: {
    'ID hệ thống': 'id',
    'Tên kho': 'store_name',
    'Tổng tồn': 'total_quantity',
  },
  crm_quy: {
    'ID hệ thống': 'id',
    'Mã quỹ': 'fund_code',
    'Tên quỹ': 'fund_title',
    'Mô tả quỹ': 'fund_description',
    'Quỹ cha (ID)': 'fund_parent_id',
    'Người quản lý (ID)': 'fund_manager',
    'Thủ quỹ (ID)': 'fund_cashier',
    'Người duyệt (ID)': 'fund_approver',
    'Số dư đầu': 'start_money',
    'Số dư đầu kỳ': 'opening_balance',
    'Tổng tiền': 'total_money',
    'Tài khoản tài chính': 'financial_account',
    'TK đối ứng': 'reciprocal_account',
    'TK thuế': 'tax_account',
    'Mã ngân sách': 'budget_id',
    'Dùng quy trình': 'use_process',
    'Vô hiệu': 'invalid',
    'Thời gian bắt đầu': 'time_start',
  },
  crm_pt_thanh_toan: {
    'ID hệ thống': 'id',
    'Tên PT thanh toán': 'method_name',
    'Hiệu lực': 'valid',
  },
  crm_trao_doi: {
    'ID hệ thống': 'id',
    'Mã KH (ID)': 'account_id',
    'Họ tên khách hàng': 'account_name',
    'Mối quan hệ KH': 'account_relation_name',
    'Nội dung trao đổi': 'content',
    'Tiêu đề': 'comment_title',
    'Ngày tạo': 'created_at',
    'Người tạo': 'creator_display_name',
    'Người tạo (ID)': 'creator',
    'Người được gắn thẻ': 'tagged_users',
    'Là phản hồi': 'is_feedback',
    'Avatar KH': 'account_avatar',
    'Quan hệ KH (ID)': 'account_relation_id',
  },
};
