ALTER TABLE IF EXISTS dim_hom
ADD COLUMN IF NOT EXISTS "Ten_mkt" TEXT,
ADD COLUMN IF NOT EXISTS "Ten_ky_thuat" TEXT,
ADD COLUMN IF NOT EXISTS "Ten_Hom_The_Hien" TEXT,
ADD COLUMN IF NOT EXISTS "Ten_chuan_hoa" TEXT,
ADD COLUMN IF NOT EXISTS "Goi_dich_vu" TEXT,
ADD COLUMN IF NOT EXISTS "Mau_Sac" TEXT,
ADD COLUMN IF NOT EXISTS "Loai_san_pham" TEXT,
ADD COLUMN IF NOT EXISTS "Ton_giao" TEXT,
ADD COLUMN IF NOT EXISTS "Dac_diem" TEXT,
ADD COLUMN IF NOT EXISTS "Nap" TEXT,
ADD COLUMN IF NOT EXISTS "Liet" TEXT,
ADD COLUMN IF NOT EXISTS "Be_mat" TEXT;
